//File generated by Flavo Header Tool. DO NOT edit unless you are sure you know what to do
#pragma once

#include "Global.h"
#include "EECS.h"
typedef eecs::SystemBase*(*CreateObjectOfTypeFunc)();
typedef eecs::ComponentBase*(*CreateComponentOfTypeFunc)();

template<typename T> //primary system template
eecs::SystemBase* createObjectOfType() { return new T(); }

template<typename T> //primary component template
eecs::ComponentBase* createComponentOfType() { return new T(); }

namespace ft_engine { class Metadata; }
template<> eecs::ComponentBase* createComponentOfType<ft_engine::Metadata>();

namespace ft_engine { class CharacterController; }
template<> eecs::ComponentBase* createComponentOfType<ft_engine::CharacterController>();

namespace ft_engine { class Collider; }
template<> eecs::ComponentBase* createComponentOfType<ft_engine::Collider>();

namespace ft_engine { class FixedJoint; }
template<> eecs::ComponentBase* createComponentOfType<ft_engine::FixedJoint>();

namespace ft_engine { class ResolveConstraintsSystem; }
template<> eecs::SystemBase* createObjectOfType<ft_engine::ResolveConstraintsSystem>();

namespace ft_engine { class Rigidbody; }
template<> eecs::ComponentBase* createComponentOfType<ft_engine::Rigidbody>();

namespace ft_engine { class RigidbodySystem; }
template<> eecs::SystemBase* createObjectOfType<ft_engine::RigidbodySystem>();

namespace ft_engine { class Transform; }
template<> eecs::ComponentBase* createComponentOfType<ft_engine::Transform>();

namespace ft_engine { class TransformSystem; }
template<> eecs::SystemBase* createObjectOfType<ft_engine::TransformSystem>();

namespace ft_engine { class TriggerCollider; }
template<> eecs::ComponentBase* createComponentOfType<ft_engine::TriggerCollider>();

namespace ft_render { class Camera; }
template<> eecs::ComponentBase* createComponentOfType<ft_render::Camera>();

namespace ft_render { class CylinderLight; }
template<> eecs::ComponentBase* createComponentOfType<ft_render::CylinderLight>();

namespace ft_render { class DirectionalLight; }
template<> eecs::ComponentBase* createComponentOfType<ft_render::DirectionalLight>();

namespace ft_render { class PointLight; }
template<> eecs::ComponentBase* createComponentOfType<ft_render::PointLight>();

namespace ft_render { class RenderSystem; }
template<> eecs::SystemBase* createObjectOfType<ft_render::RenderSystem>();

namespace ft_render { class SkinnedMeshRenderer; }
template<> eecs::ComponentBase* createComponentOfType<ft_render::SkinnedMeshRenderer>();

namespace ft_render { class StaticMeshRenderer; }
template<> eecs::ComponentBase* createComponentOfType<ft_render::StaticMeshRenderer>();

namespace reflection
{
	class Serializer
	{
	public:
		Serializer();
		~Serializer();

		void initRootComponent(eecs::Entity entity) const;

		const std::unordered_map<std::string, CreateObjectOfTypeFunc>& getSystemCreationMap() const;
		const std::unordered_map<std::string, CreateComponentOfTypeFunc>& getComponentCreationMap() const;
		const std::unordered_map<std::string, uint32>& getComponentTypeMap() const;

		const std::unordered_map<uint32, std::string>& getTypeComponentMap() const;

	private:
		std::unordered_map<std::string, CreateObjectOfTypeFunc> systemCreationMap_;
		std::unordered_map<std::string, CreateComponentOfTypeFunc> componentCreationMap_;
		std::unordered_map<std::string, uint32> componentTypeMap_;
		std::unordered_map<uint32, std::string> typeComponentMap_;
	}; //class Serializer
} //namespace reflection

namespace reflection
{
	enum class ComponentEnum
	{
		Metadata = 0,
		CharacterController = 1,
		Collider = 2,
		FixedJoint = 3,
		Rigidbody = 4,
		Transform = 5,
		TriggerCollider = 6,
		Camera = 7,
		CylinderLight = 8,
		DirectionalLight = 9,
		PointLight = 10,
		SkinnedMeshRenderer = 11,
		StaticMeshRenderer = 12,
	}; //enum class ComponentEnum
} //namespace reflection
